# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql-proxy
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3310
    targetPort: 3306
  clusterIP: None
  selector:
    app: mysql
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the master: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: mysql
  labels:
    app: mysql
spec:
  externalIPs:
  - 124.116.157.15
  ports:
  - name: mysql
    protocol: TCP
    port: 3311
    targetPort: 3306
  selector:
    app: mysql

