kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-1
  namespace: mysql
spec:
  capacity:
    storage: 30Gi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: "/mysql-cluster"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-2
  namespace: mysql
spec:
  capacity:
    storage: 30Gi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: "/mysql-cluster"

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-3
  namespace: mysql
spec:
  capacity:
    storage: 30Gi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: "/mysql-cluster"
